baseURL = "https://blog.wholesomevalue.com"
languageCode = "en-us"
title = "full of wholesome values"
theme = "book"
[outputs]
  home = ["HTML", "RSS", "JSON"]
[params]
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = false
[markup.goldmark.renderer]
  unsafe = true
